### ISSUE TITLE
install failure : (

### ISSUE THREAD

**Issue by kumavis** [robertboloc/lolcatjs#2]
```
╭─kumavis@xyzs-MacBook-Pro  ~/dev/web3-provider-skeleton ‹node-v0.12.7›  (master*) 
╰─$ npm install -g lolcatjs                                                                                                                                                                             1 ↵
/Users/kumavis/.nvm/versions/node/v0.12.7/bin/lolcatjs -> /Users/kumavis/.nvm/versions/node/v0.12.7/lib/node_modules/lolcatjs/cli.js

> sleep@2.0.0 install /Users/kumavis/.nvm/versions/node/v0.12.7/lib/node_modules/lolcatjs/node_modules/sleep
> node-gyp rebuild

  CXX(target) Release/obj.target/node_sleep/sleep.o
../sleep.cc:36:3: error: use of undeclared identifier 'NanScope'
  NanScope();
  ^
../sleep.cc:38:7: error: use of undeclared identifier 'args'; did you mean 'uv_process_options_s::args'?
  if (args.Length() < 1 || !args[0]->IsUint32()) {
      ^~~~
      uv_process_options_s::args
/Users/kumavis/.node-gyp/0.12.7/deps/uv/include/uv.h:857:10: note: 'uv_process_options_s::args' declared here
  char** args;
         ^
../sleep.cc:38:7: error: invalid use of non-static data member 'args'
  if (args.Length() < 1 || !args[0]->IsUint32()) {
      ^~~~
../sleep.cc:38:29: error: use of undeclared identifier 'args'; did you mean 'uv_process_options_s::args'?
  if (args.Length() < 1 || !args[0]->IsUint32()) {
                            ^~~~
                            uv_process_options_s::args
/Users/kumavis/.node-gyp/0.12.7/deps/uv/include/uv.h:857:10: note: 'uv_process_options_s::args' declared here
  char** args;
         ^
../sleep.cc:38:29: error: invalid use of non-static data member 'args'
  if (args.Length() < 1 || !args[0]->IsUint32()) {
                            ^~~~
../sleep.cc:39:12: error: use of undeclared identifier 'NanThrowError'; did you mean 'Nan::ThrowError'?
    return NanThrowError("Expected number of seconds");
           ^~~~~~~~~~~~~
           Nan::ThrowError
../../nan/nan.h:651:3: note: 'Nan::ThrowError' declared here
  X(Error)
  ^
../../nan/nan.h:639:21: note: expanded from macro 'X'
    NAN_INLINE void Throw ## NAME(const char *msg) {                           \
                    ^
<scratch space>:102:1: note: expanded from here
ThrowError
^
../sleep.cc:42:9: error: use of undeclared identifier 'args'; did you mean 'uv_process_options_s::args'?
  sleep(args[0]->Uint32Value());
        ^~~~
        uv_process_options_s::args
/Users/kumavis/.node-gyp/0.12.7/deps/uv/include/uv.h:857:10: note: 'uv_process_options_s::args' declared here
  char** args;
         ^
../sleep.cc:42:9: error: invalid use of non-static data member 'args'
  sleep(args[0]->Uint32Value());
        ^~~~
../sleep.cc:44:3: error: use of undeclared identifier 'NanReturnUndefined'
  NanReturnUndefined();
  ^
../sleep.cc:48:3: error: use of undeclared identifier 'NanScope'
  NanScope();
  ^
../sleep.cc:50:7: error: use of undeclared identifier 'args'; did you mean 'uv_process_options_s::args'?
  if (args.Length() < 1 || !args[0]->IsUint32()) {
      ^~~~
      uv_process_options_s::args
/Users/kumavis/.node-gyp/0.12.7/deps/uv/include/uv.h:857:10: note: 'uv_process_options_s::args' declared here
  char** args;
         ^
../sleep.cc:50:7: error: invalid use of non-static data member 'args'
  if (args.Length() < 1 || !args[0]->IsUint32()) {
      ^~~~
../sleep.cc:50:29: error: use of undeclared identifier 'args'; did you mean 'uv_process_options_s::args'?
  if (args.Length() < 1 || !args[0]->IsUint32()) {
                            ^~~~
                            uv_process_options_s::args
/Users/kumavis/.node-gyp/0.12.7/deps/uv/include/uv.h:857:10: note: 'uv_process_options_s::args' declared here
  char** args;
         ^
../sleep.cc:50:29: error: invalid use of non-static data member 'args'
  if (args.Length() < 1 || !args[0]->IsUint32()) {
                            ^~~~
../sleep.cc:51:12: error: use of undeclared identifier 'NanThrowError'; did you mean 'Nan::ThrowError'?
    return NanThrowError("Expected number of microseconds");
           ^~~~~~~~~~~~~
           Nan::ThrowError
../../nan/nan.h:651:3: note: 'Nan::ThrowError' declared here
  X(Error)
  ^
../../nan/nan.h:639:21: note: expanded from macro 'X'
    NAN_INLINE void Throw ## NAME(const char *msg) {                           \
                    ^
<scratch space>:102:1: note: expanded from here
ThrowError
^
../sleep.cc:54:10: error: use of undeclared identifier 'args'; did you mean 'uv_process_options_s::args'?
  usleep(args[0]->Uint32Value());
         ^~~~
         uv_process_options_s::args
/Users/kumavis/.node-gyp/0.12.7/deps/uv/include/uv.h:857:10: note: 'uv_process_options_s::args' declared here
  char** args;
         ^
../sleep.cc:54:10: error: invalid use of non-static data member 'args'
  usleep(args[0]->Uint32Value());
         ^~~~
../sleep.cc:56:3: error: use of undeclared identifier 'NanReturnUndefined'
  NanReturnUndefined();
  ^
../sleep.cc:61:16: error: use of undeclared identifier 'NanNew'
  exports->Set(NanNew<String>("sleep"), NanNew<FunctionTemplate>(Sleep)->GetFunction());
               ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/node_sleep/sleep.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/kumavis/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/Users/kumavis/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/kumavis/.nvm/versions/node/v0.12.7/lib/node_modules/lolcatjs/node_modules/sleep
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:sleep@2.0.0 sleep@2.0.0 install: `node-gyp rebuild`
npm WARN install:sleep@2.0.0 Exit status 1
/Users/kumavis/.nvm/versions/node/v0.12.7/lib
└─┬ lolcatjs@1.0.2 
  ├── ansi@0.3.0 
  ├── line-by-line@0.1.4 
  ├── minimist@1.2.0 
  ├─┬ multiline@1.0.2 
  │ └─┬ strip-indent@1.0.1 
  │   └── get-stdin@4.0.1 
  └─┬ terminal-kit@0.10.9 
    ├── async-kit@0.5.10 
    ├── string-kit@0.1.21 
    └── tree-kit@0.5.6 

npm WARN In lolcatjs@1.0.2 replacing bundled version of minimist with minimist@1.2.0
npm WARN In lolcatjs@1.0.2 replacing bundled version of multiline with multiline@1.0.2
npm WARN In lolcatjs@1.0.2 replacing bundled version of ansi with ansi@0.3.0
npm WARN In lolcatjs@1.0.2 replacing bundled version of line-by-line with line-by-line@0.1.4
npm WARN In lolcatjs@1.0.2 replacing bundled version of sleep with sleep@2.0.0
npm WARN In lolcatjs@1.0.2 replacing bundled version of terminal-kit with terminal-kit@0.10.9
npm WARN In lolcatjs@1.0.2 replacing bundled version of strip-indent with strip-indent@1.0.1
npm WARN In lolcatjs@1.0.2 replacing bundled version of get-stdin with get-stdin@4.0.1
npm WARN In lolcatjs@1.0.2 replacing bundled version of nan with nan@2.1.0
npm WARN In lolcatjs@1.0.2 replacing bundled version of string-kit with string-kit@0.1.21
npm WARN In lolcatjs@1.0.2 replacing bundled version of tree-kit with tree-kit@0.5.6
npm WARN In lolcatjs@1.0.2 replacing bundled version of async-kit with async-kit@0.5.10
```

**Comment by robertmarsal** [comment]
Hello,

This looks like a problem of the optional dependency `sleep`. It needs to compile some `C++` code during install, so depending on your setup it might fail. Can you please try with `npm install -g lolcatjs --no-optional`? This will skip the installation of the `sleep` package, meaning the animation part of the library will not look as good as it should but it should still work.

Thanks

**Comment by kumavis** [comment]
yeah it ran despite these failures. and then #3
